### ISSUE TITLE
Will not run

### ISSUE THREAD

**Issue by gbiagomba** [jh00nbr/Phishruffus#1]
Hello,

I tried running the program and it exists every time I feed it a timeout and a file to look through. I tried a big text file for the list and a small, I tried changing the timeout number. All to no avail, it runs and instantly closes. 

![image](https://user-images.githubusercontent.com/5851606/32387762-e4efbfa8-c09b-11e7-97ac-d0aaa9a2da50.png)

**Comment by jh00nbr** [comment]
Hello,

Do you have Whatsapp?




 Jhonathan Davi

Insight Security 

CEO e Founder

 

mobile: 61 98322-5371 / 61 9 8256-3462

site: www.insightsecurity.com.br / lab.insightsecurity.com.br

email: jdavi@insightsecurity.com.br

skype: jonatas.davi

 ...
 
 






---- On Sex, 03 nov 2017 15:35:52 -0200 Brotha Darkness &lt;notifications@github.com&gt; wrote ----




Hello,

I tried running the program and it exists every time I feed it a timeout and a file to look through. I tried a big text file for the list and a small, I tried changing the timeout number. All to no avail, it runs and instantly closes.

**Comment by gbiagomba** [comment]
@jh00nbr No I do not (anymore) but I have signal

**Comment by jh00nbr** [comment]
Hello friend, I made an update in the code, try again!




 Jhonathan Davi

Insight Security 

CEO e Founder

 

---- On Ter, 07 nov 2017 17:39:44 -0200 Brotha Darkness &lt;notifications@github.com&gt; wrote ----




@jh00nbr No I do not (anymore) but I have signal

**Comment by gbiagomba** [comment]
Awesome it worked!
